### ISSUE TITLE
Publish an official chocolatey package

### ISSUE THREAD

**Issue by jo-chemla** [LibreHardwareMonitor/LibreHardwareMonitor#903]
A lot of organizations are using Chocolatey to manage packages installed on a batch of hosts. However, the deprecated unofficial chocolatey package for libre-hardware-monitor stalls at v 0.8.5. It would help to have official choco packages for libre-hardware-monitor so that orgs would not be forced to rely on the older open-hardware-monitor - for which an official choco package exists. 

Since Github CI auto builds and packs exe and lib in a zip archive every new release, it seems like it should be straightforward, even directly using github actions or auto-updated module. It might help to follow the [quickstart-guide](https://docs.chocolatey.org/en-us/create/create-packages-quick-start) with [automatic packages](https://docs.chocolatey.org/en-us/create/automatic-packages) - the recommended way is to use [Chocolatey automatic updater module](https://github.com/majkinetor/au)

Related : #321 which was closed without pushing a choco package.

**Comment by jo-chemla** [comment]
Note: [winget-releaser](https://github.com/marketplace/actions/winget-releaser) is a Github Action made for winget automatic package deployment during CI. Could probably replace the choco package, and be easier to implement if a Github Action CI workflow is already set-up.

**Comment by jo-chemla** [comment]
@moellerm, @PhyxionNL, are you interested in a PR for the winget-releaser github action workflow on every github release? 

The winget `LibreHardwareMonitor.LibreHardwareMonitor` package could be auto-updated on every github release. Here is a reference article based on [Winget-Releaser@v2 Github Action](https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-). + Below is an action yml files made to keep the winget package up-to-date on every github release, via Github Actions. 

Requires:
 - You will need to create a classic Personal Access Token (PAT) with `public_repo` scope.
 - This token should be added as a repository secret by creating a [new repo secret](https://github.com/Jacalz/rymdport/settings/secrets/actions/new) with name `WINGET_ACC_TOKEN` and value the token
 - Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under the same account/organization as the project's repository. If you are forking winget-pkgs on a different account (e.g. bot/personal account), you can use the fork-user input to specify the username of the account where the fork is present.

```yaml
name: Publish to WinGet
on:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: LibreHardwareMonitor.LibreHardwareMonitor
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: ' LibreHardwareMonitor\w*\.zip$'
```
